### ISSUE TITLE
error: undefined reference to 'OPENSSL_cpuid_setup'

### ISSUE THREAD

**Issue by bzzbzz7** [tbfly/openssl-1.0.1t4android#1]
I compile the respone ,result :
     error: undefined reference to 'OPENSSL_cpuid_setup'
what's wrong?

**Comment by tbfly** [comment]
What's your NDK version?

**Comment by bzzbzz7** [comment]
thank you for replay. I have solved the problem. the problem is I download the git zip file on win7 and unzip it ,then copy the unzip files to ubuntu platform which is not the same system. when I download the git zip file on ubuntu ,it works well!

**Comment by tbfly** [comment]
😄
